sudo: false

language: java

jdk:
  - oraclejdk8

env:
  global:
    secure: "cwcbZHRjNFAAZvQd8fd8WhDfB7vpzkGED+ANMGxi4gnBsHPbjZrQnrV6Du9KKNb+eQMcrMuuMEO3H23lZ+W2awGQ1FCdNBe9AxkWMcitXOHfRabIeIhqtqDFBfEdlumzAdTEss/UhEBVWTWE+033HstEbgegmoIBsfF7CvhYaCM="

install: mvn dependency:go-offline

script: mvn -Plibrary verify

cache:
  directories:
    - $HOME/.m2

after_success:
  - git clone https://github.com/perfectsense/travis-maven-deploy.git && travis-maven-deploy/deploy.sh
